---
-  name: installing api version of spurt commerce
   become: yes
   hosts: all
   vars:
     - root_user: root
     
   tasks:
     - name: installing nodesource
       ansible.builtin.shell:
         cmd: "curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -"
       become: yes
       become_user: "{{ root_user }}"