---
-  name: installing api version of spurt commerce
   become: yes
   hosts: all
   vars:
     - image_magick: imagemagick
     - angular_package: '@angular/cli'
     - spurtcommerce_path: /home/devops/spurtcommerce
     - spurt_repo: 'https://github.com/Manojkumarpolaka/spurtcommerce.git'
     - spurt_version: 3.0.2
      
     
   tasks:
     - name: installing nodesource
       ansible.builtin.shell:
         cmd: "curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -"
       become: yes
       become_user: 
     - name: installing nodejs
       command:
         cmd: "sudo apt install nodejs"
     - name: installing build-essential
       apt:
         name: build-essential
     - name: installing nodejs libraries
       npm:
         name: "{{ item }}"
         global: yes
       loop: 
         - forever  
         - apidoc  
     - name: installing apache2
       apt:
         name: apache2
         update_cache: yes    
     - name: Enable the Apache2 modules
       apache2_module:
         name: proxy
         state: present
     - name: Enable the Apache2 modules
       apache2_module:
         name: proxy_http
         state: present
     - name: Enable the Apache2 modules
       apache2_module:
         name: headers
         state: present
     - name: restarting apache2
       ansible.builtin.systemd:
         name: apache2
         daemon_reload: yes
         state: restarted
     - name: installing mysql
       apt:
         name: mysql-server
         state: present
     - name: Install python3-PyMySQL library
       apt:
         name: python3-pymysql
         state: present
     - name: update mysql root password for root account
       mysql_user:
         name: root
         login_unix_socket: /var/run/mysqld/mysqld.sock
         login_user: root
         login_password: mysql@123
         host: 'localhost'
         password: mysql@123
         priv: "*.*:ALL,GRANT"
         check_implicit_admin: true
         state: present    
     - name: starting mysql-server
       ansible.builtin.systemd:
         name: mysql.service
         state: started
     - name: installing imagemagick
       apt:
         name: "{{ image_magick }}"
         state: present
     - name: installing angular
       npm:
         name: "{{ angular_package }}"
         state: present
         global: yes
     - name: installing git
       apt:
         name: git
         state: present
     - name: cloning git
       git:
         repo: 'https://github.com/Manojkumarpolaka/spurtcommerce.git'
         dest: "{{ spurtcommerce_path }}"
         clone: yes
         force: 'yes'
     - name: apache2 reverse proxy
       template: 
         dest: /etc/apache2/sites-available/000-default.conf
         src: apacheproxy.j2
       notify: restarting apache2
     - name: changing user and group
       file: 
         path: "{{ spurtcommerce_path }}"
         owner: devops
         group: devops
         recurse: yes
    
     - name: import the database
       mysql_db:
         name: sprutcommerce
         state: import
         target: "/home/devops/spurtcommerce/spurtcommerce.sql"
         login_host: 'localhost'
         login_user: root
         login_password: mysql@123   
     - name: Install packages based on package.json for backend API.
       npm:
         path: "{{ spurtcommerce_path }}/api"
         state: latest
     - name: Building the application for backend API
       command:
         chdir: "{{ spurtcommerce_path }}/api"
         cmd: npm install typeorm-seeding@1.0.0-beta.6 -- save
     - name: Building the application for backend API
       command:
         chdir: "{{ spurtcommerce_path }}/api"
         cmd: npm run build
     - name: Setting Git Repo user name
       git_config:
         name: user.name
         repo: "{{ spurtcommerce_path }}"
         scope: global
         value: 'spurtcommerce'
     - name: Setting Git Repo user safe.directory
       git_config:
         name: safe.directory
         repo: "{{ spurtcommerce_path }}"
         scope: global
     - name: Setting Git Repo user email
       git_config:
         name: user.email
         repo: "{{ spurtcommerce_path }}"
         scope: global
         value: 'spurtcommerce@gmail.com'
     - name: Downloading spurtcommerce
       git:
         repo: "{{ spurt_repo }}"
         dest: "{{ spurtcommerce_path }}"
         clone: yes
     - name: Installing unzip
       apt:
         name: unzip
         state: present
     - name: Extracting spurtcommerce
       unarchive: 
         src: "{{ spurtcommerce_path }}/Spurtcommerce_{{spurt_version}}_community_LTS.zip"
         dest: "{{ spurtcommerce_path }}"
         remote_src: yes
     - name: changing user and group
       file: 
         path: "{{ spurtcommerce_path }}"
         owner: devops
         group: devops
         recurse: yes
     - name: Adding DB username, password and database in .env
       template:
         src: '.env.j2'
         dest: 'spurtcommerce/Spurtcommerce_{{spurt_version}}_community_LTS/api/.env'
     - name: Adding DB username, password and database in .env.production 
       template:
         src: '.env.production.j2'
         dest: 'spurtcommerce/Spurtcommerce_{{spurt_version}}_community_LTS/api/.env.production'
     - name: Install packages based on package.json for backend API.
       npm:
         path: "{{ spurtcommerce_path }}/Spurtcommerce_{{spurt_version}}_community_LTS/api"
         state: latest
     - name: Building the application for backend API
       command:
         chdir: "{{ spurtcommerce_path }}/Spurtcommerce_{{spurt_version}}_community_LTS/api"
         cmd: npm install typeorm-seeding@1.0.0-beta.6 -- save

       
    

       

   handlers: 
     - name: restarting apache2
       ansible.builtin.systemd:
         name: apache2.service
         daemon_reload: yes
         enabled: yes
         state: restarted
     
         

          