---
-  name: installing api version of spurt commerce
   become: yes
   hosts: all
   vars:
     - root_user: root
     - login_socket: /var/run/mysqld/mysqld.sock
     - mysql_user: root
     - mysql-password: mysql@123
     
   tasks:
     - name: installing nodesource
       ansible.builtin.shell:
         cmd: "curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -"
       become: yes
       become_user: "{{ root_user }}"
     - name: installing nodejs
       command:
         cmd: "sudo apt install nodejs"
     - name: installing build-essential
       apt:
         name: build-essential
     - name: installing nodejs libraries
       npm:
         name: "{{ item }}"
         global: yes
       loop: 
         - forever  
         - apidoc  
     - name: installing apache2
       apt:
         name: apache2
         update_cache: yes    
     - name: Enable the Apache2 modules
       apache2_module:
         name: proxy
         state: present
     - name: Enable the Apache2 modules
       apache2_module:
         name: proxy_http
         state: present
     - name: Enable the Apache2 modules
       apache2_module:
         name: headers
         state: present
     - name: restarting apache2
       ansible.builtin.systemd:
         name: apache2
         daemon_reload: yes
         state: restarted
     - name: installing mysql
       apt:
         name: mysql-server
         state: present
     - name: Install python3-PyMySQL library
       apt:
         name: python3-pymysql
         state: present
     - name: update mysql root password for root account
       mysql_user:
         name: "{{ mysql_user }}"
         login_unix_socket: "{{ login_socket }}"
         login_user: "{{ mysql_user }}"
         login_password: "{{ mysql-password }}"
         host: 'localhost'
         password: "{{ mysql-password }}"
         priv: "*.*:ALL,GRANT"
         check_implicit_admin: true
         state: present    
     - name: starting mysql-server
       ansible.builtin.systemd:
         name: mysql.service
         state: started
