---
-  name: installing api version of spurt commerce
   become: yes
   hosts: all
   vars:
     - root_user: root
     
   tasks:
     - name: installing nodesource
       ansible.builtin.shell:
         cmd: "curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -"
       become: yes
       become_user: "{{ root_user }}"
     - name: installing nodejs
       command:
         cmd: "sudo apt install nodejs"
     - name: installing build-essential
       apt:
         name: build-essential
     - name: installing nodejs libraries
       npm:
         name: "{{ item }}"
         global: yes
       loop: 
         - forever  
         - apidoc  
     - name: installing apache2
       apt :
         name: apache2
         update_cache: yes    